/*
 * This Kotlin source file was generated by the Gradle 'init' task.
 */
package com.github.jomof.prefab.plugin

import org.gradle.testfixtures.ProjectBuilder
import kotlin.test.Test


class PrefabPluginTest {
    @Test fun `plugin registers task`() {
        // Create a test project and apply the plugin
        val project = ProjectBuilder.builder().build()
        project.plugins.apply("prefab-plugin")
        project.extensions.getByType(PrefabPluginExtension::class.java)

        // Verify the result
        //assertNotNull(project.tasks.findByName("buildAllPrefab"))
    }
}
