name: CI
on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
    steps:
      - uses: actions/checkout@v2
      - name: Build 
        run: ./gradlew publish --info --stacktrace
        env:
          USERNAME: jomof
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

